ChelsiAlise/workingdogdatadash

utils/parse_data.py

This adds some utility code to parse the dog data.

Parse data files

---

utils/parse_data.py

This adds a new default parser that parses individual dog data files instead of aggregate files.
It also cleans up `utils/parse_data.py` a bit in general.

Parse individual dog data files

---

utils/gen_db.py
utils/gen_db_local.py
utils/parse_data.py

Create initial database generation script.

Generate database

---

app.yaml
routes.go
static/index.html
static/login.html

This adds a proof of concept login system.
We absolutely need to replace this in the future, but we needed this ASAP and in-between finals so....
Additionally, routes that aren't static assets are now authorized behind this system, and all pages are served with HTTPS only.

add POC login

---

memcache.go

This adds simple caching to the datastore on top of memcached.
TODO: expire cached data in the DB, perhaps change how long data is cached in memcached.
The data is currently static so this is fine for now, but in the future this will need to be revisited.

add simple caching to DB

---

utils/parse_data.py

This adds code to the utils scripts to process the outcome data when dumped to `./../CCI Puppy Data/outcomes.csv`
This is part of work for #18

add outcome data parsing

---

data.go
utils/upload_data.py

this is part of completing #18

add outcome data fields to server and upload script

---

dev_server.py

route customChart.html in the dev server for now

---

routes.go
utils/parse_data.py
utils/upload_data.py

This improves the upload system as outlined in #51

improve upload system

---

memcache.go

Fix caching system

---

static/customChart.html
static/dashboard.js
static/index.html

Removing the sidebar and making custom graphs at tab at the top for the time being. Data still not loading correctly from the api though. Fyi The branch name is remove chart js but I did not do that and I forgot to create a branch with an accurate description. Sorry

Removing the sidebar and making custom graphs at tab at the top for the

---

static/customChart.html

Custom Graphs work with api calls. Added the ability to zoom with line graphs.

Custom Graphs working with DB

---

utils/parse_data.py
utils/upload_data.py

this is a minor tweak to the data processing and upload pipeline used to track which dogs have discrepant data and to suppress previous excessive debug output (the entire json blob).

print out dogs that are missing outcomes

---

static/index.html
static/index.js

Fix zoom reset button placement on dashboard graphs so the button no longer blocks the legend.

Fix zoom reset on dashboard

---

static/index.css
static/index.html
static/index.js

This improves the user interface a bit, especially on mobile; mostly by again removing whitespace, adding sharp borders, and centering the stats tables.
This also removes some unused CSS rules.
This is part of #16.

Improve User Interface Styling

---

utils/parse_points.py

This adds parse_points to the utils folder, for parsing the new data set.
This is part of #63

add code to parse points data

---

static/index.html
static/index.js

altered the region graph on the dashboard to display percentages of time
for awake, active and rest in proportion to total time. Also centered
the dashboard layout as it was not centered anymore.

altered the region graph on the dashboard to display percentages with respect to total time

---

static/index.html
static/index.js

Added multi line comparison graphs for Juma showing percentage of total
time in rest active and awake

Added multi line comparison graphs

---

data.go
datastore.go
gen_keys.py
routes.go
utils/hash.go
utils/upload_user.py

moves user account info into cloud datastore

move user info to cloud datastore

---

dev_server.py

@jedmpaz this should fix things for you hopefully.

print port as decimal

---

static/highcharts/highcharts-regression-master/LICENSE
static/highcharts/highcharts-regression-master/README.md
static/highcharts/highcharts-regression-master/highcharts-regression.js
static/highcharts/highcharts-regression-master/manifest.json
static/index.html
static/index.js

This functionality is a plugin so these extra high chart files are
needed in order for it to work

Addition of regression lines to scatter plot graphs

---

data.go
utils/parse_data.py
utils/upload_data.py

this updates the parsers and data formats for the new outcome data.

add updated outcome data

---

data.go
datastore.go
memcache.go
routes.go
utils/parse_data.py
utils/upload_data.py

hotfix for timeouts when cache is cleared and more data is loaded.

Increase context timeouts

---

memcache.go
routes.go

this improves the performance of all pages

cache user info in memcache

---

static/index.html
static/index.js

Fixed a bug where Pie chart was not registering filtered dog.
Fixed a bug where Line chart button was not showing up.
Added brief help about filtering.

bug fixes and help added

---

datastore.go
routes.go

this adds administrator (user management) apis

add admin apis

---

README.md
memcache.go
routes.go
utils.go

This closes #74.
NOTE: we still need more useful "help" content in the UI @ChelsiAlise @william7hsu @branden14k @jedmpaz.

cleanup routing and write initial readme

---

data.go
datastore.go
routes.go
utils/parse_data.py
utils/upload_points.py

This was used to import the points data set.

add tooling and apis for the points data set

---

static/index.js

Fixed positioning of the pie chart on the dashboard graph and removed some commented out logging.

Fixed positioning of the pie chart on the dashboard graph

---

static/index.html
static/index.js

Makes the pie chart a separate chart below instead on being on top of the graph

Seperate pie chart

---

static/index.css
static/index.html
static/index.js

This greatly improves the custom graphs UX.
This closes #109, #108, #107.
This supersedes #110.

Improved custom graphs

---

static/index.js

for some reason some of the dates aren't ordered correctly. this simple fix should solve that.
be aware of this in any other graphs if you add any...

fix bug with handling out of order dates in some graphs

---

README.md
static/index.html
utils/README.md

This adds documentation required for the customer delivery docs assignment

add some updated documentation
